title: "Ganji Sreeram"
markdown: CommonMarkGhPages
remote_theme: pmarsceill/just-the-docs


# just-the-docs options
# Aux links for the upper right navigation
aux_links:
  "LinkedIn":
    - "https://www.linkedin.com/in/ganjisreeram/"
  "Google Scholar":
    - "https://scholar.google.co.in/citations?user=5TtVp4AAAAAJ&hl=en&oi=ao"
    
aux_links_new_tab: true

# search:
#   button: true
  
  
# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

theme: jekyll-theme-cayman